#!/usr/bin/php
<?php
	define('BASEPATH', '.');
	require_once('application/config/database.php');
	if ($argc == 5)
	{
		($handler = fopen('application/config/database.php', 'w+')) or die ("Application is not availible");
		fputs($handler, "<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
");
		fputs($handler, '$active_group = "default";
$active_record = TRUE;
');
		$db['default']['hostname'] = $argv[1];
		$db['default']['username'] = $argv[2];
		$db['default']['password'] = $argv[3];
		$db['default']['database'] = $argv[4];
		$keys = array_keys($db['default']);
		foreach($keys as $key)
		{
			fputs($handler, '$db[\'default\'][\''.$key.'\'] = "'.$db['default'][$key].'";
');
		}
		fclose($handler);
		echo "To finish the installation please visit \"main/finish\" \n";
	}
	else
	{
		echo "Command usage is: install <dbhost> <dbusername> <dbpassword> <dbname> \n";
	}
?>
